name: parent_migration

on:
  workflow_dispatch:
  #pull_request:
  #  branches:
  #    - "main" 
  #push:
  #  branches:
  #    - "main" 



jobs:
  dev_deployment:
    name: dev_deployment
    # This line specifies a dependency between this job and the test_migration job
    # This line specifies an environment dependency.  Environments are how you can require a reviewer to approve
    # a workflow before it can run.  This is useful if you want to make sure that the code is reviewed before it runs
    uses: ./.github/workflows/child_databricks_deployment.yml
    with:
      tenant_id: e17c0f0c-6ff0-4c72-9fa8-b5aa41b420e8
      subscription_id: a793e3af-d8ae-490f-9e17-a5b33025f02d
      workspace_url: https://adb-953700043831947.7.azuredatabricks.net
      repo_path: ./notebooks
      databricks_path: /Shared/deployed_notebooks
      github_environment: dev
      
    secrets:
      client_id: ${{ secrets.client_id }}
      client_secret: ${{ secrets.client_secret }}

  
  prod_deployment:
    name: prod_deployment
    # This line specifies an environment dependency.  Environments are how you can require a reviewer to approve
    # a workflow before it can run.  This is useful if you want to make sure that the code is reviewed before it runs
    needs: [dev_deployment]
    uses: ./.github/workflows/child_databricks_deployment.yml
    with:
      tenant_id: e17c0f0c-6ff0-4c72-9fa8-b5aa41b420e8
      subscription_id: a793e3af-d8ae-490f-9e17-a5b33025f02d
      workspace_url: https://adb-8820818186366613.13.azuredatabricks.net
      repo_path: ./notebooks
      databricks_path: /Shared/deployed_notebooks
      github_environment: prod
      
    secrets:
      client_id: ${{ secrets.client_id }}
      client_secret: ${{ secrets.client_secret }}
  
